package droid.maxander.rainbowkeyboard

class LevelResources {
    val level1ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        100
    )
    val level2ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        8
    )
    val level3ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        8
    )
    val level4ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        16
    )
    val level5ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        3
    )
    val level6ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        6
    )
    val endlessArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        6
    )
    val level21ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        100
    )
    val level22ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        4
    )
    val level23ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        8
    )
    val level24ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        6
    )
    val level25ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        10
    )
    val level26ArrayButtons= listOf(
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        30//8
    )
    val level31ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        100//6
    )
    val level32ArrayButtons= listOf(
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_2,
        R.drawable.cube_2,
        3
    )
    val level33ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_3,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_2,
        R.drawable.cube_1,
        9
    )
    val level34ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_2,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_2,
        6
    )
    val level35ArrayButtons= listOf(
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_2,
        R.drawable.cube_3,
        5
    )
    val level36ArrayButtons= listOf(
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_3,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_1,
        R.drawable.cube_3,
        10
    )
}